### ISSUE TITLE
Removing obsureHeaders from log at all

### ISSUE THREAD

**Issue by trance4mation** [tellnes/bunyan-middleware#4]
Hi Christian,
wouldn't be good idea to completely remove headers defined in obsureHeaders from the request? At this time, they are set to null, which creates unnecessary long and not-so-good readable bunyan-cli logs:

```
GET /js/homeController.min.js HTTP/1.1
    host: localhost:3030
    connection: null
    cache-control: null
    accept: */*
    if-none-match: null
    if-modified-since: Tue, 17 Feb 2015 19:56:25 GMT
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36
    referer: http://localhost:3030/
    accept-encoding: gzip, deflate, sdch
    accept-language: null
    x-powered-by: null
    x-request-id: null
```

This output is produced by line:

```
headers[ obscureHeaders[i] ] = null
```

I suggest to replace it with:

```
delete headers[ obscureHeaders[i] ]
```

Best regards,
Jiri

**Comment by tellnes** [comment]
Yeah, I was unsure how to handle this when I implement the feature. The reason I did set it to `null` in favor of deleting it was so the logs would include that the header did exists.

I see two solution to this problem.

1. Just remove them instead of setting it to `null`.
2. Introduce a new `removeHeaders` property which removes the headers.
  - Optionaly change the value for `obscureHeaders` from `null` to eg. `'<hidden>'`.

**Comment by gillesdemey** [comment]
I'm more in favour of explicitly changing the values to `<hidden>` to indicate that we've made a deliberate choice to hide them. 

I can imagine that removing the fields might complicate a post-mortem when trying to find the cause of a failed request.

**Comment by tellnes** [comment]
I'm open to pull requests.
